# syntax=docker/dockerfile:1
FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/.

# mount a cache to not re-download all requirements every time requirements.txt changes
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

CMD ["gunicorn", "main:app", "--worker-class", "gevent", "--bind", "0.0.0.0:8001"]