services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    volumes:
      - chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}    
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    environment:
      - OLLAMA_SERVER_URL="http://ollama:11434"
    ports:
      - 8001:8001
    volumes:
      - .:/app
    # entrypoint: ["sleep", "10000"]

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434

volumes:
  chromadb:
  ollama: